### PR TITLE
Spotify refresh

### LINKED ISSUE #54: Spotify token refresh
#52 is not working yet. After an hour, the next playback stops with Spotify auth errors.

After investigation its because Supabase + Spotify uses the the authorization code flow which requires the client secret to refresh, which isn't possible on the browser side.

I found this Supabase issue and put some details there: https://github.com/supabase/auth/issues/1450#issuecomment-2479325369

### PR DESCRIPTION
**Pull request by nzoschke**
- Token table to persist Spotify refresh tokens
- Save token after login
- Call Supabase function that has client secret to refresh

Fixes #54 ?

TODO

- [x] Auto deploy function
- [x] Function env
- [ ]  Save refresh token and expiry and conditionally call token func

### CODE REVIEW

File: src/lib/types/database.ts [hunk 1]
```diff
@@ -44,15 +44,25 @@ export type Database = {
...
         };
-        Relationships: [
-          {
-            foreignKeyName: "channels_user_id_fkey";
-            columns: ["user_id"];
-            isOneToOne: false;
-            referencedRelation: "users";
-            referencedColumns: ["id"];
-          },
-        ];
```
Comment (nzoschke) [inline src/lib/types/database.ts:55]: Is this intentional?

Comment (nzoschke) [reply src/lib/types/database.ts:55]: no but it doesn't affect anything.
